#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

IMAGE="${IMAGE:-maxsonferovante/fraud-detection-resources}"
TAG="${1:-$(date +'%d-%m-%Y-%H-%M-%S')}"
PLATFORMS="${PLATFORMS:-linux/amd64,linux/arm64}"

RES_DIR="${ROOT}/resources"
DOCKERFILE_RES="${ROOT}/Dockerfile.resources"
DOCKERFILE_MAIN="${ROOT}/Dockerfile"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "error: missing required command: $1" >&2
    exit 1
  }
}

need_cmd cargo
need_cmd curl
need_cmd docker

mkdir -p "${RES_DIR}"

fetch_if_missing() {
  local url="$1"
  local out="$2"
  if [[ -s "${out}" ]]; then
    return 0
  fi
  echo "downloading: ${url}"
  curl -fL --retry 3 --retry-delay 1 "${url}" -o "${out}"
}

fetch_if_missing \
  "https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2026/main/resources/mcc_risk.json" \
  "${RES_DIR}/mcc_risk.json"
fetch_if_missing \
  "https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2026/main/resources/normalization.json" \
  "${RES_DIR}/normalization.json"
fetch_if_missing \
  "https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2026/main/resources/references.json.gz" \
  "${RES_DIR}/references.json.gz"

echo "running preprocessor (native SIMD)..."
(cd "${ROOT}" && RUSTFLAGS="-C target-cpu=native -C opt-level=3" cargo run --release --bin preprocessor)

if [[ ! -s "${RES_DIR}/specialist.bin" ]]; then
  echo "error: expected ${RES_DIR}/specialist.bin to be generated by preprocessor" >&2
  exit 1
fi

TMPDIR="${TMPDIR:-/tmp}"
CTX_DIR="$(mktemp -d "${TMPDIR%/}/rinha-resources.XXXXXX")"
cleanup() {
  rm -rf "${CTX_DIR}"
}
trap cleanup EXIT

cp -f "${RES_DIR}/specialist.bin" "${CTX_DIR}/specialist.bin"
cp -f "${RES_DIR}/normalization.json" "${CTX_DIR}/normalization.json"
cp -f "${RES_DIR}/mcc_risk.json" "${CTX_DIR}/mcc_risk.json"

echo "building and pushing resources image: ${IMAGE}:${TAG} (${PLATFORMS})"
docker buildx build \
  --platform "${PLATFORMS}" \
  --push \
  -f "${DOCKERFILE_RES}" \
  -t "${IMAGE}:${TAG}" \
  "${CTX_DIR}"

echo "resolving manifest digest for ${IMAGE}:${TAG}"
DIGEST="$(docker buildx imagetools inspect "${IMAGE}:${TAG}" | awk '/^Digest:/ {print $2; exit}')"
if [[ -z "${DIGEST}" ]]; then
  echo "error: could not resolve digest for ${IMAGE}:${TAG}" >&2
  exit 1
fi

PINNED_REF="${IMAGE}@${DIGEST}"
echo "pinning main Dockerfile to: ${PINNED_REF}"

perl -pi -e "s|^ARG RESOURCES_IMAGE=.*$|ARG RESOURCES_IMAGE=${PINNED_REF}|m" "${DOCKERFILE_MAIN}"

echo "done."
echo "resources image: ${IMAGE}:${TAG}"
echo "pinned ref:      ${PINNED_REF}"

